zpshch/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'mainapp.views.home', name='home_url'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^([a-z]+)/$', 'mainapp.views.board', name='board_url'),
    url(r'^change_rating/$', 'mainapp.views.change_rating', name='change_rating'),
    url(r'^add_comment/$', 'mainapp.views.add_comment', name='add_comment'),
)

mainapp/models.py
from django.db import models

# Create your models here.


class Board(models.Model):
    title = models.CharField(max_length=200)
    shortcut = models.CharField(max_length=10)

    def __str__(self):
        return '{0} (/{1}/)'.format(self.title, self.shortcut)


class Thread(models.Model):
    # class for both threads and comments
    title = models.CharField(max_length=200, blank=True)  # only for threads
    text = models.TextField()
    author = models.CharField(max_length=200, blank=True, default='аноним')
    board = models.ForeignKey(Board, blank=True, null=True)  # only for threads
    parent = models.ForeignKey('self', blank=True, null=True)  # only for comments
    timestamp = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return '(to {0}): {1}'.format(self.board if self.board else self.parent.id, self.text[:100])

mainapp/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render
from django.template import Template, Context

from mainapp.models import Board, Thread


def main_processor(request):
    return {
        'boards': Board.objects.all(),
    }


def home(request):
    return render(request, 'home.html', {})


def board(request, shortcut):
    board = Board.objects.get(shortcut=shortcut)
    threads = Thread.objects.filter(board=board)
    return render(request, 'board.html', {'board': board, 'threads': threads})


def change_rating(request):
    # ajax POST request
    thread_id = request.POST['thread_id']
    delta = int(request.POST['delta'])
    t = Thread.objects.get(id=thread_id)
    t.rating += delta
    t.save()

    return HttpResponse(json.dumps({
        'new_rating': t.rating,
    }), mimetype='application/json')


def add_comment(request):
    # ajax POST request
    comment = Thread()
    comment.parent = Thread.objects.get(id=int(request.POST['thread_id']))
    comment.text = request.POST['text'].strip()
    author = request.POST['author'].strip()
    if author:
        comment.author = author
    comment.save()

    return HttpResponse(json.dumps({
        'id': '{0:06}'.format(comment.id),
        'timestamp': Template('{{dt}}').render(Context({'dt': comment.timestamp})),
        'author': comment.author,
        'text': comment.text,
    }), mimetype='application/json')

mainapp/templates/base.html
    <html>
    <head>
        <title>ЗПШЧ: {% block title %}без название{% endblock %}</title>
        <meta charset="utf8">
        <link rel="stylesheet" href="{{ STATIC_URL }}css/main.css">
        <script src="{{ STATIC_URL }}js/jquery-1.9.1.min.js"></script>
        <script src="{{ STATIC_URL }}js/main.js"></script>
    </head>

    <body>
        {% block navigation %}
            {% for board in boards %}
                <a href="{% url 'board_url' board.shortcut %}">{{ board.title }} (/{{ board.shortcut }}/)</a> 
                {% if not forloop.last %}|{% endif %}
            {% endfor %}
        {% endblock %}
        {% block body %}
            Здесь ничего нет
        {% endblock %}
    </body>
</html>

mainapp/templates/board.html
{% extends "base.html" %}

{% load utils %}

{% block title %}{{ board.title }}{% endblock %}

{% block body %}
        <h2>{{ board.title }}</h2>

        <div class="threads">
        {% for thread in threads %}
            <div class="thread" data-id="{{ thread.id }}">
                <div class="ch-block">
                    <span class="id">
                        {{ thread.id|leading_zeros:6 }}
                    </span>
                    <span class="rating">
                        <span class="rating-plus" data-id="{{ thread.id }}">+</span>
                        <span class="rating-value" data-id="{{ thread.id }}">{{ thread.rating }}</span>
                        <span class="rating-minus" data-id="{{ thread.id }}">&minus;</span>
                    </span>
                    <span class="timestamp">
                        {{ thread.timestamp }}                    
                    </span>

                    <div class="ch-block-header">
                        <h3 class="title">{{ thread.title }}</h3>
                        <span class="author">автор: {{ thread.author }}</span>
                    </div>

                    <div class="text">
                    {{ thread.text }}
                    </div>
                </div>
                <div class="comments">
                {% for comment in thread.thread_set.all %}
                    <div class="comment ch-block">
                        <span class="id">
                            {{ comment.id|leading_zeros:6 }}
                        </span>
                        <span class="rating">
                            <span class="rating-plus" data-id="{{ comment.id }}">+</span>
                            <span class="rating-value" data-id="{{ comment.id }}">{{ comment.rating }}</span>
                            <span class="rating-minus" data-id="{{ comment.id }}">&minus;</span>
                        </span>
                        <span class="timestamp">
                            {{ comment.timestamp }}                    
                        </span>

                        <div class="ch-block-header">   
                            <span class="author">автор: {{ comment.author }}</span>
                        </div>

                        <div class="text">
                        {{ comment.text }}
                        </div>
                    </div>
                {% endfor %}
                </div>
                <div class="response-div comment ch-block">
                    <form>
                        <label for="author">Автор:</label>
                        <input type="text" name="author">
                        <br>
                        <label for="text">Комментарий:</label>
                        <br>
                        <textarea name="text"></textarea>
                        <br>
                        <input type="button" value="Ответить">
                    </form>
                </div>
            </div>
            {% if not forloop.last %}
            <hr>
            {% endif %}
        {% endfor %}
        </div>
{% endblock %}

mainapp/templates/home.html
{% extends "base.html" %}

{% block title %}главная{% endblock %}

{% block body %}
        <h2>Добро пожаловать на ЗПШЧ</h2>

        <ul>
        {% for board in boards %}
            <li><a href="/{{ board.shortcut }}/">{{ board.title }}</a></li>
        {% endfor %}
        </ul>
{% endblock %}